# Metadata about this component, to be used in the CMS
spec: {}

# Defines the structure of this component, as well as the default values
blueprint:
  label: ""
  number: 3

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: Label

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
