name: Committee on Data in Research
author: Nick Jones
url: https://dir-aotearoa.github.io/
about: >-
  The purpose of this committee is to bring together experts, communities and
  organisations involved in the production, measurement, collection, storage,
  and use of data in research. The term “research” is interpreted broadly, and
  includes aspects of data use in business and industry. 


  Research is increasingly interdisciplinary, as illustrated by global grand challenges of the kind embodied in the UN Sustainable Development Goals, the Sendai Framework (2015-2030), Paris Climate Agreement (UNFCC 2015), and the Habitat III New Urban Agenda (United Nations Habitat III 2016), and this requires the development of new connections between people and between organisations. Sharing best practice and building relationships, both nationally and internationally, will add value to the work that we do, and open up new opportunities for collaborative research with enhanced benefit to Aotearoa New Zealand. 


  The Committee will foster a sense of community among those interested in Data. The Committee and its community should have a clarity of purpose and a shared vision that reflects the values and principles embodied in Te Tiriti o Waitangi, all the way from gathering, measuring, storing, to using and reusing data, and everything in between.
